# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j_ankle1_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_ankle1_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_ankle2_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_ankle2_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_high_arm_l:
    has_velocity_limits: true
    max_velocity: 5.648668
    has_acceleration_limits: false
    max_acceleration: 0
  j_high_arm_r:
    has_velocity_limits: true
    max_velocity: 5.648668
    has_acceleration_limits: false
    max_acceleration: 0
  j_low_arm_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_low_arm_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_pan:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_pelvis_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_pelvis_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_shoulder_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_shoulder_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_thigh1_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_thigh1_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_thigh2_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_thigh2_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_tibia_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_tibia_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_tilt:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_wrist_l:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  j_wrist_r:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0