network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses: [10.42.0.2/24]
      gateway4: 10.42.0.1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4,1.1.1.1]

