sudo apt-get install ros-melodic-gazebo-ros-control -y
sudo apt-get install ros-melodic-ros-controllers -y
sudo apt-get install ros-melodic-ros-control -y
sudo apt-get install ros-melodic-controller-manager -y
sudo apt-get install ros-melodic-effort-controllers -y
sudo apt-get install ros-melodic-joint-state-controller -y
sudo apt-get install ros-melodic-moveit-kinematics -y
sudo apt-get install ros-melodic-dynamixel-sdk -y
sudo apt-get install ros-melodic-moveit-core -y
sudo apt-get install ros-melodic-moveit-ros-planning-interface -y
