sudo apt-get install ros-kinetic-gazebo-ros-control
sudo apt-get install ros-kinetic-ros-controllers
sudo apt-get install ros-kinetic-ros-control
sudo apt-get install ros-kinetic-controller-manager
sudo apt-get install ros-kinetic-effort-controllers
sudo apt-get install ros-kinetic-joint-state-controller
sudo apt-get install ros-kinetic-dynamixel-sdk
sudo apt-get install ros-kinetic-moveit-kinematics
sudo apt-get install ros-kinetic-genpy
