# HSV PARAM CONFIGURATIONS

hsv_h_min: 0  
hsv_h_max: 70
hsv_s_min: 215
hsv_s_max: 255
hsv_v_min: 0
hsv_v_max: 255

# HLS PARAM CONFIGURATION
hls_h_min: 0  
hls_h_max: 82
hls_l_min: 108
hls_l_max: 232
hls_s_min: 0
hls_s_max: 255

# CAMERA PARAMETERS
rgb8: false
use_hsv: true