controller_list:
  - name: fake_leg_left_controller
    joints:
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
      - left_knee_pitch
      - left_ankle_pitch
      - left_ankle_roll
  - name: fake_leg_right_controller
    joints:
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee_pitch
      - right_ankle_pitch
      - right_ankle_roll
  - name: fake_arm_left_controller
    joints:
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_elbow_pitch
  - name: fake_arm_right_controller
    joints:
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_elbow_pitch